spring:
  profiles: test
  datasource:
    url: jdbc:hsqldb:esu
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  devtools:
    livereload.enable: true

logging:
  level:
    org.davidmendoza: debug
#    org.springframework: debug
